version: "3.8"

services:
  postgres:
    image: "postgres:16.4"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
  redis:
    image: "redis:7.4.0"
    ports:
      - "6379:6379"